services:
  klipper:
    image: "miob/klipper:latest"
    restart: "unless-stopped"
    privileged: true
    volumes:
      - "./config:/opt/data/config"
      - "comms:/opt/data/comms"
      - "gcodes:/opt/data/gcodes"
      - "/dev:/dev"

  moonraker:
    image: "miob/moonraker:latest"
    restart: "unless-stopped"
    depends_on:
      - "klipper"
      - "klipper-docs"
    volumes:
      - "moonraker-backup:/opt/data/backup"
      - "./config:/opt/data/config"
      - "comms:/opt/data/comms"
      - "moonraker-database:/opt/data/database"
      - "gcodes:/opt/data/gcodes"
      - "logs:/opt/data/logs"
      - "klipper-config:/opt/klipper/config"
      - "klipper-docs:/opt/klipper/docs"
    labels:
      traefik.enable: true
      traefik.http.routers.moonraker.rule: "PathPrefix(`/websocket`, `/server/`, `/printer`, `/access`, `/machine`)"
      traefik.http.routers.moonraker.entrypoints: "web"
      traefik.http.services.moonraker.loadbalancer.server.port: 7125

  mainsail:
    image: "ghcr.io/mainsail-crew/mainsail:latest"
    restart: "unless-stopped"
    labels:
      traefik.enable: true
      traefik.http.routers.mainsail.rule: "PathPrefix(`/`)"
      traefik.http.routers.mainsail.entrypoints: "web"
  
  traefik:
    image: "traefik:v2.10"
    restart: "unless-stopped"
    command:
      - "--accesslog"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  klipper-docs:
    image: "miob/klipper:latest"
    entrypoint: "bash -c 'cp -r /opt/klipper/docs /opt/data/klipper/docs && cp -r /opt/klipper/config /opt/data/klipper/config'"
    volumes:
      - "klipper-config:/opt/data/klipper/config"
      - "klipper-docs:/opt/data/klipper/docs"
volumes:
  moonraker-backup:
  comms:
    driver_opts:
      type: tmpfs
      device: tmpfs
  moonraker-database:
  gcodes:
  logs:
    driver_opts:
      type: tmpfs
      device: tmpfs
  klipper-config:
    driver_opts:
      type: tmpfs
      device: tmpfs
  klipper-docs:
    driver_opts:
      type: tmpfs
      device: tmpfs