name: Docker Image CI

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
        description: 'app image to build'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Build the Docker image
        run: ./scripts/build_image.sh ${{ inputs.app }} miob/ --push
