name: Docker Image CI

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
        description: 'app image to build'
env:
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: ./scripts/build_image.sh ${{ inputs.app }} ${{ env.REGISTRY }}/miob/ --push
