name: Klipper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-image.yml
    with:
      app: klipper
